### Autogenerated - DO NOT EDIT
aliases="template=template-service"
runnableJars="template-service=template-service/template-service/target/template-service.jar"
ports="template-service=http/8080,debug/4000"
